### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rubyurek** [mabu95/PhoUI#1]
**Describe the bug**
The action bar cannot be edited and the 3 action bar cannot be edited properly.

**To Reproduce**
1. Go to 'Edit Mode'
2. Click on 'Actionbar 3'

**Expected behavior**
You should be able to edit the action bars

**Screenshots**
![Screenshot_9](https://user-images.githubusercontent.com/42946288/211146337-cfe92924-cda9-4625-9bb0-976eaa44b613.png)

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Comment by mabu95** [comment]
Fixed in Version 1.1.2
