### ISSUE TITLE
WOW calendar, actionbars

### ISSUE THREAD

**Issue by Axlfuy** [mabu95/PhoUI#2]
Can you make it so if we right-click the clock, calendar would open?
"/click GameTimeFrame"
This is the macro I'm currently using to open it.

Also if we have PhoUI Actionbar disabled, can you fix the _skinning_ that's still happening?
Addon enabled:
![image](https://user-images.githubusercontent.com/6570086/211192154-52529c6c-1a1a-4394-a8de-c8e82da3ffe9.png)

Addon disabled:
![image](https://user-images.githubusercontent.com/6570086/211192226-73e323ec-4052-4282-819d-d8c2d0752b0f.png)

**Comment by mabu95** [comment]
You have now the Option to disable the PhoUI Actionbar Button.
Note: You can only disable the Button, when you disabled the PhoUI Actionbar.

Mouse3(Wheel-Click) will open Calendar. Maybe i change it later on Codechanges.
