### ISSUE TITLE
Enemy castbar

### ISSUE THREAD

**Issue by Axlfuy** [mabu95/PhoUI#3]
Shield icon on uninterruptible spells is scuffed.
![image](https://user-images.githubusercontent.com/6570086/211193207-d4f8cf8e-252d-4573-8a8a-7e6cea8be2e7.png)

And now that I'm looking more closely, the gold ring around the enemy portrait should be the same color as the dragon, silver for rare elite.

Oh yeah this is triggering my OCD
![image](https://user-images.githubusercontent.com/6570086/211193351-121892c2-d933-492a-afb8-4fe951b13c2d.png)
Can you move it a few pixels so it's right in the center?

**Comment by mabu95** [comment]
Fixed in 1.13
