### ISSUE TITLE
Player and Target unitframes

### ISSUE THREAD

**Issue by Axlfuy** [mabu95/PhoUI#5]
Ok here I go with more troubleshooting xD

When in Raid, your name and the group you are in overlaps
![image](https://user-images.githubusercontent.com/6570086/211214529-bc631ebe-5906-4986-af27-7d336b68695a.png)

Sometimes role icon is on the wrong place
![image](https://user-images.githubusercontent.com/6570086/211214560-61caf4e8-a6dc-4e85-8293-c9facc85d3b8.png)

When you have buff on top for target unitframe, name is obstructed by the buffs
![image](https://user-images.githubusercontent.com/6570086/211214599-5ae4f32d-5745-41f4-89ce-a09c7b4153b9.png)

Maybe when you have big style unitframes, make an option to put the name inside the unitframe (top center of healthbar)? An X  Y  setting for buffs on target unitframe? Just throwing some ideas.  
Love the addon, keep up the good job!

Edit: Just reproduced the icon on a weird spot: when you mount up on those dragons to move to another part of the dungeon/raid (RLP, Vault of the Incarnates), when landing the role icon is in the wrong place.

**Comment by mabu95** [comment]
Fill be fixed on the next Update
