### ISSUE TITLE
PVP icon on target unitframe, Edit Mode

### ISSUE THREAD

**Issue by Axlfuy** [mabu95/PhoUI#6]
PvP icon overlapped by level indicator. Also I have _PvP Icon_ addon setting unchecked and still shows it
![image](https://user-images.githubusercontent.com/6570086/211523995-a609556c-305d-4532-a52f-0023baf2677a.png)

Bunch of graphical issues with castbar shield icon when in edit mode
![image](https://user-images.githubusercontent.com/6570086/211524696-1461c323-2891-4818-b20a-e9605917db53.png)

**Comment by Peggin** [comment]
The PvP icon is still an issue
