### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JusttDan** [mabu95/PhoUI#8]
**Describe the bug**
`31x PhoUI/Modules/Actionbar/Custom.lua:99: attempt to index local 'LeftEndCap' (a nil value)
[string "@PhoUI/Modules/Actionbar/Custom.lua"]:99: in function `SetPosition'
[string "@PhoUI/Modules/Statusbar/Statusbar.lua"]:32: in function <PhoUI/Modules/Statusbar/Statusbar.lua:18>
[string "@PhoUI/Modules/Statusbar/Statusbar.lua"]:204: in function <PhoUI/Modules/Statusbar/Statusbar.lua:161>

Locals:
self = PhoUIActionbar {
 SetPosition = <function> defined @PhoUI/Modules/Actionbar/Custom.lua:85
 Background = Texture {
 }
 0 = <userdata>
}
StatusbarCount = 2
LeftEndCap = nil
RightEndCap = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "CENTER"
(*temporary) = UIParent {
 0 = <userdata>
 Tabs = <table> {
 }
 ContainerFrames = <table> {
 }
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = "BOTTOM"
(*temporary) = 0
(*temporary) = 39
(*temporary) = "attempt to index local 'LeftEndCap' (a nil value)"
Actionbar = PhoUIActionbar {
 SetPosition = <function> defined @PhoUI/Modules/Actionbar/Custom.lua:85
 Background = Texture {
 }
 0 = <userdata>
}`

**Which World of Warcraft version (please complete the following information):**
 - Retail

**Additional context**
This error is constant, within 5 minutes of play time ther's 101 events with this error.

**Comment by mabu95** [comment]
Which Version are you currently running? And what Settings are u Using on PhoUI->Actionbar (Screenshot would help a lot)

**Comment by JusttDan** [comment]
I'm running 10.0.1

![image](https://user-images.githubusercontent.com/44147439/213876442-d931ccb7-ae39-43b3-9208-5e5f597db794.png)

**Comment by mabu95** [comment]
Set a Gryphon-Style (empty will occur errors). I will fix it on the next Update (for Empty States).
https://prnt.sc/XgFnygZ9h25i

**Comment by JusttDan** [comment]
Yea, that's sorted it. Nice one!
